const LENDER_CATALOG = {
  OVLY: {
    name: "Olyv Finance", logo: "/Olyv_Logo.webp",
    maxAmount: 200000, minInterest: 18,
    processingTime: "3-5 Days", approval: "VERY GOOD",
    website: `https://app.olyv.co.in/login?utm_source=Ratecut&utm_campaign=Ratecut_link1&utm_medium={utm_medium}`,
    apr: 12.5, tag: "Top Pick", type: "NBFC · AAA rated",
    rateRange: "12% – 18% p.a.", processingFee: "1% of loan amount",
    prepayment: "Nil", disbursal: "Same day",
    docs: ["PAN", "Aadhaar", "Bank statement", "Salary slip"],
  },
  FATAKPAY: {
    code: 'FATAKPAY',
    name: 'Fatak Pay', logo: '/fatak_pay.webp',
    maxAmount: 100000, minInterest: 18,
    processingTime: '1-2 Days', approval: 'VERY GOOD',
    website: 'https://web.fatakpay.com/authentication/login?utm_source=708_8FQLQ&source_caller=api&shortlink=708_8FQLQ&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 16.5, tag: 'Pre-Approved', type: 'Fintech · Quick',
    rateRange: '12% – 20% p.a.', processingFee: '2%+GST of loan amount',
    prepayment: 'Nil', disbursal: '1-2 business days',
    docs: ['PAN', 'Aadhaar'],
  },
  CRMPaisa: {
    code: 'CRMPaisa',
    name: 'Emergency Paisa', logo: '/ep.png',
    maxAmount: 100000, minInterest: 16,
    processingTime: '1-2 Days', approval: 'EXCELLENT',
    website: 'https://emergencypaisa.com/apply-now?utm_source=RCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 36, type: 'Digital · Quick',
    rateRange: '16% – 36% p.a.', processingFee: '2% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  MPOKKET: {
    code: 'MPOKKET',
    name: 'mPokket', logo: '/mpokket.svg',
    maxAmount: 50000, minInterest: 18.96,
    processingTime: '3-5 Days', approval: 'EXCELLENT',
    website: 'https://web.mpokket.in/?utm_source=ratecut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 25, tag: 'Salaried Only', type: 'Student · Gig',
    rateRange: '15% – 25% p.a.', processingFee: '₹37.5 - ₹200',
    prepayment: 'Nil', disbursal: '1-3 business days',
    docs: ['PAN', 'Aadhaar'],
  },
  MPOKKETSE: {
    code: 'MPOKKETSE',
    name: 'mPokket', logo: '/mpokket.svg',
    maxAmount: 200000, minInterest: 18.96,
    processingTime: '3-5 Days', approval: 'EXCELLENT',
    website: 'https://web.mpokket.in/?utm_source=ratecut_bl&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 25, tag: 'Self-Employed Only', type: 'Self-Employed',
    rateRange: '15% – 25% p.a.', processingFee: '₹37.5 - ₹200',
    prepayment: 'Nil', disbursal: '1-3 business days',
    docs: ['PAN', 'Aadhaar'],
  },
  RAMFINCROP: {
    code: 'RAMFINCROP',
    name: 'Ram Fincorp', logo: '/ramfincorp.png',
    maxAmount: 100000, minInterest: 18,
    processingTime: '1-3 Days', approval: 'EXCELLENT',
    website: 'https://applyonline.ramfincorp.com/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 35, tag: 'Pre-Approved', type: 'NBFC · Regional',
    rateRange: '12% – 35% p.a.', processingFee: '1%-5% of loan amount',
    prepayment: '2% after 6 months', disbursal: '1-3 business days',
    docs: ['PAN', 'Aadhaar', 'Bank statement'],
  },
  INDIALENDS: {
    code: 'INDIALENDS',
    name: 'IndiaLends', logo: '/IL-logo.svg',
    maxAmount: 200000, minInterest: 10.5,
    processingTime: '0-1 Day', approval: 'GOOD',
    website: 'https://partners.indialends.com/RateCut?sub_source=IND&ref_id=77D908AB-7C2E-4E26&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '10.5% – 30% p.a.', processingFee: 'Upto 2.5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  PoonawallaFincorp: {
    code: 'PoonawallaFincorp',
    name: 'Poonawalla Fincorp', logo: '/poonawalla.svg',
    maxAmount: 500000, minInterest: 9.99,
    processingTime: '0-1 Day', approval: 'GOOD',
    website: 'https://instant-pocket-loan.poonawallafincorp.com/?redirectto=primepl&utm_DSA_Code=7857&UTM_Partner_AgentCode=Inderpreet@ratecut.in_DSA&UTM_Partner_Name=DSA_RAAJ_KHOSLA_&_COMPANY_PRIVATE_LIMITED&UTM_SM_Name=ashish.gupta33649@poonawallafincorp.com&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 18, type: 'NBFC · AAA rated',
    rateRange: '9% – 18% p.a.', processingFee: 'Upto 3% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Bank statement', 'Salary slip'],
  },
  CreditSea: {
    code: 'CreditSea',
    name: 'CreditSea', logo: '/creditsea.png',
    maxAmount: 50000, minInterest: 14,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://www.creditsea.com/onboarding/sign-up/enter-mobile?source=12850119&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 18, type: 'Digital · Quick',
    rateRange: '15% – 24% p.a.', processingFee: 'Upto 5.1%+GST of loan amount',
    prepayment: 'Nil', disbursal: '0-1 day',
    docs: ['PAN', 'Aadhaar', 'Bank statement', 'ITR'],
  },
  SPEEDO: {
    code: 'SPEEDO',
    name: 'Speedo Loan', logo: '/speedo.png',
    maxAmount: 100000, minInterest: 25,
    processingTime: '1-2 Days', approval: 'EXCELLENT',
    website: 'https://loanapply.speedoloan.com/?partner_id=ratecut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 20, tag: 'Salaried Only', type: 'NBFC · Fast',
    rateRange: '16% – 24% p.a.', processingFee: '1% of loan amount',
    prepayment: 'Nil', disbursal: '1-2 business days',
    docs: ['PAN', 'Aadhaar', 'Bank statement'],
  },
  TrueFund: {
    code: 'TrueFund',
    name: 'True Fund', logo: '/TrueFundLogo.png',
    maxAmount: 40000, minInterest: 25,
    processingTime: '1-2 Days', approval: 'EXCELLENT',
    website: 'https://truefund.in/short-term-loan/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 20, tag: 'Salaried Only', type: 'NBFC · Fast',
    rateRange: '16% – 24% p.a.', processingFee: '1% of loan amount',
    prepayment: 'Nil', disbursal: '1-2 business days',
    docs: ['PAN', 'Aadhaar'],
  },
  TAP4CREDIT: {
    code: 'TAP4CREDIT',
    name: 'Tap4Credit', logo: '/tap4credit-logo.png',
    maxAmount: 50000, minInterest: 15,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://tap4credit.in/short-term-loan/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  Prefr: {
    code: 'Prefr',
    name: 'Prefr', logo: '/prefrIcon.svg',
    maxAmount: 500000, minInterest: 21.49,
    processingTime: '0-1 Days', approval: 'GOOD',
    website: 'https://marketplace.prefr.com/zet?utm_source=ZET&utm_content=content1&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 23.25, type: 'NBFC · Fast',
    rateRange: '21% – 24% p.a.', processingFee: '1% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  HERO: {
    code: 'HERO',
    name: 'Hero Fincorp', logo: '/herofincorp.webp',
    maxAmount: 500000, minInterest: 18,
    processingTime: '0-1 Day', approval: 'GOOD',
    website: 'https://hipl.onelink.me/S7fO?af_ios_url=https%3A%2F%2Floans.apps.herofincorp.com%2Fen%2Fpersonal-loan&af_android_url=https%3A%2F%2Floans.apps.herofincorp.com%2Fen%2Fpersonal-loan&af_xp=custom&pid=Partnership&is_retargeting=true&af_reengagement_window=30d&c=ZetApp&utm_source=partnership&utm_campaign=ratecut_website&utm_content=ZPRCLC&utm_medium={utm_medium}',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 2.5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  RupeeDhan: {
    code: 'RupeeDhan',
    name: 'RupeeDhan', logo: '/rdlogo.svg',
    maxAmount: 100000, minInterest: 30,
    processingTime: '0-1 Day', approval: 'GOOD',
    website: 'https://rupeedhan.com/short-term-loan/?utm_source=ratecut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, tag: 'Salaried Only', type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 2.5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  PaisaBoxx: {
    code: 'PaisaBoxx',
    name: 'PaisaBoxx', logo: '/PB_logo.png',
    maxAmount: 35000, minInterest: 30,
    processingTime: '0-1 Day', approval: 'GOOD',
    website: 'https://www.paisaboxx.com/?partner_id=54987eaae1&source=ratecut&campaign=delhi&campaign_source=ratecut123&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, tag: 'Salaried Only', type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 2.5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  Cashvia: {
    code: 'Cashvia',
    name: 'Cashvia', logo: '/cashvia_logo.png',
    maxAmount: 50000, minInterest: 14,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://spectrum.gotrackier.com/click?campaign_id=1796&pub_id=930&source=ratecut_web&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 3% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  DigiCredit: {
    code: 'DigiCredit',
    name: 'Digi Credit', logo: '/digicredit_logo.png',
    maxAmount: 50000, minInterest: 20,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://spectrum.gotrackier.com/click?campaign_id=1776&pub_id=930&source=ratecut_web&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  AdityaBirla: {
    code: 'AdityaBirla',
    name: 'Aditya Birla Capital', logo: '/aditya_logo.png',
    maxAmount: 500000, minInterest: 10,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://spectrum.gotrackier.com/click?campaign_id=631&pub_id=930&source=%7Bratecut_web%7D&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  AdityaBirlaPL: {
    code: 'AdityaBirlaPL',
    name: 'Aditya Birla Capital PL', logo: '/aditya_logo.png',
    maxAmount: 200000, minInterest: 10.99,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://spectrum.gotrackier.com/click?campaign_id=637&pub_id=930&url_id=4&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar'],
  },
  SabkaLoan: {
    code: 'SabkaLoan',
    name: 'Sabka Loan', logo: '/sabkaloan_logo.png',
    maxAmount: 100000, minInterest: 30,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://sabkaloan.com/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, tag: 'Salaried Only', type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Salary Slip', 'Bank Statement'],
  },
  Banxx: {
    code: 'Banxx',
    name: 'Banxx Personal Loan', logo: '/banxx_logo.png',
    maxAmount: 100000, minInterest: 20,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://banxx.com/in/loans/app/zkedCGIL/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, tag: 'Salaried Only', type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Salary Slip', 'Bank Statement'],
  },
  BanxxBL: {
    code: 'BanxxBL',
    name: 'Banxx Business Loan', logo: '/banxx_logo.png',
    maxAmount: 500000, minInterest: 11,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://banxx.com/in/business-loans/app/zkedCGIL/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, tag: 'Self Employed Only', type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Bank Statement'],
  },
  BanxxGL: {
    code: 'BanxxGL',
    name: 'Banxx Gold Loan', logo: '/banxx_logo.png',
    maxAmount: 300000, minInterest: 10,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://banxx.com/in/gold-loans/app/zkedCGIL/?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Bank Statement'],
  },
  Bajaj: {
    code: 'Bajaj',
    name: 'Bajaj Markets', logo: '/bajaj.png',
    maxAmount: 200000, minInterest: 10,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://www.bajajfinservmarkets.in/apply-for-personal-loan-finservmarkets?utm_source=RateCut&utm_medium={utm_medium}&utm_campaign=ratecut_website',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Salary Slip', 'Bank Statement'],
  },
  ZYPE: {
    code: 'ZYPE',
    name: 'Zype', logo: '/Zype_svg_black.svg',
    maxAmount: 200000, minInterest: 18,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://portal.getzype.com/?utm_campaign=web_Ratecut&utm_source=RateCut&utm_medium={utm_medium}',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Bank Statement'],
  },
  LendingPlate: {
    code: 'LendingPlate',
    name: 'Lending Plate', logo: '/LendingPlate Logo.gif',
    maxAmount: 250000, minInterest: 18,
    processingTime: '0-1 Day', approval: 'EXCELLENT',
    website: 'https://lendingplate.com/personal-loan-lead-form?utm_source=RATECUT&utm_campaign=RATECUT&utm_medium={utm_medium}#applynow',
    apr: 24, type: 'Fintech · Quick',
    rateRange: '15% – 30% p.a.', processingFee: 'Upto 5% of loan amount',
    prepayment: 'Nil', disbursal: 'Same day',
    docs: ['PAN', 'Aadhaar', 'Bank Statement'],
  },
};
 
const DEFAULT_LENDER_ORDER = [
  'RAMFINCROP', 'MPOKKET', 'PoonawallaFincorp', 'MPOKKETSE', 'CreditSea',
  'AdityaBirla', 'AdityaBirlaPL', 'INDIALENDS', 'Prefr', 'HERO', 'FATAKPAY',
  'SPEEDO', 'TrueFund', 'TAP4CREDIT', 'RupeeDhan', 'PaisaBoxx', 'DigiCredit',
  'Cashvia', 'SabkaLoan', 'CRMPaisa',
];

function buildLenderList(codes) {
  const order = Array.isArray(codes) && codes.length ? codes : DEFAULT_LENDER_ORDER;
  return order
    .map((code) => (LENDER_CATALOG[code] ? { ...LENDER_CATALOG[code] } : null))
    .filter(Boolean);
}

module.exports = {
  LENDER_CATALOG,
  DEFAULT_LENDER_ORDER,
  buildLenderList,
};
